=== hmrc/child-benefit-view-frontend/conf/resources/data/financial-details/Success-Response-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "API#1453 Get Child Benefit Financial Details success response Schema v1.0.0",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "debtIndicator",
    "awardInformation",
    "rateInformation"
  ],
  "properties": {
    "debtIndicator": {
      "description": "Indicates if claimant has debt on account. 1 = true, 0 = false",
      "$ref": "#/definitions/indicatorType"
    },
    "bankData": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "buildingSocietyIdentifier": {
          "type": "string",
          "minLength": 0,
          "maxLength": 2
        },
        "sortCode": {
          "type": "string",
          "minLength": 0,
          "maxLength": 15
        },
        "bankAccountNumber": {
          "type": "string",
          "minLength": 0,
          "maxLength": 18
        },
        "buildingSocietyRollNumber": {
          "type": "string",
          "minLength": 0,
          "maxLength": 20
        },
        "accountHolderName": {
          "type": "string",
          "minLength": 0,
          "maxLength": 60
        },
        "validFromDate": {
          "description": "Date format of YYYY-MM-DD",
          "$ref": "#/definitions/dateString"
        }
      }
    },
    "awardInformation": {
      "type": "array",
      "minItems": 1,
      "maxItems": 50,
      "uniqueItems": true,
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "awardValue",
          "startDate",
          "endDate"
        ],
        "properties": {
          "awardValue": {
            "$ref": "#/definitions/monetaryPosType"
          },
          "startDate": {
            "$ref": "#/definitions/dateString"
          },
          "endDate": {
            "$ref": "#/definitions/dateString"
          }
        }
      }
    },
    "rateInformation": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "higherRateValue",
        "standardRateValue",
        "guardianAllowanceRateValue"
      ],
      "properties": {
        "higherRateValue": {
          "$ref": "#/definitions/monetaryPosType"
        },
        "standardRateValue": {
          "$ref": "#/definitions/monetaryPosType"
        },
        "guardianAllowanceRateValue": {
          "$ref": "#/definitions/monetaryPosType"
        }
      }
    },
    "paymentData": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "amount",
          "dateFrom",
          "dateTo",
          "chargeRef",
          "expectedCreditingDate",
          "returnIndicator"
        ],
        "properties": {
          "amount": {
            "$ref": "#/definitions/monetaryPosNegType"
          },
          "dateFrom": {
            "$ref": "#/definitions/dateString"
          },
          "dateTo": {
            "$ref": "#/definitions/dateString"
          },
          "chargeRef": {
            "type": "string",
            "minLength": 1,
            "maxLength": 16
          },
          "expectedCreditingDate": {
            "$ref": "#/definitions/dateString"
          },
          "returnIndicator": {
            "description": "Indicates if payment has been returned by bank, 1 when payment is returned, 0 [ zero] when payment has not been returned.",
            "$ref": "#/definitions/indicatorType"
          }
        }
      }
    },
    "adjustmentType": {
      "type": "array",
      "minItems": 0,
      "uniqueItems": true,
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "adjustmentAmount",
          "adjustmentStartDate",
          "adjustmentEndDate",
          "adjustmentReasonCode"
        ],
        "properties": {
          "adjustmentAmount": {
            "$ref": "#/definitions/monetaryPosType"
          },
          "adjustmentStartDate": {
            "$ref": "#/definitions/dateString"
          },
          "adjustmentEndDate": {
            "$ref": "#/definitions/dateString"
          },
          "adjustmentReasonCode": {
            "type": "string",
            "description": "Two digit character code identifying adjustment reason. See API#1414 for the current set of strings and their meaning",
            "pattern": "^[0-9]{2}$"
          }
        }
      }
    }
  },
  "definitions": {
    "indicatorType": {
      "type": "integer",
      "enum": [
        0,
        1
      ]
    },
    "dateString": {
      "type": "string",
      "description": "Format CCYY-MM-DD",
      "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
    },
    "monetaryPosType": {
      "type": "number",
      "minimum": 0,
      "maximum": 99999999999.99,
      "multipleOf": 0.01
    },
    "monetaryPosNegType": {
      "type": "number",
      "minimum": -99999999999.99,
      "maximum": 99999999999.99,
      "multipleOf": 0.01
    }
  }
}

=== hmrc/child-benefit-view-frontend/conf/resources/des/api/child-benefit-financial-details/AB654321.json
{
  "debtIndicator": 1,
  "bankData": {
    "sortCode": "11-22-33",
    "bankAccountNumber": "987654321123456789",
    "accountHolderName": "MR JOHN DOE O'MALLEY & MRS O'MALLEY",
    "validFromDate": "1981-01-01"
  },
  "awardInformation": [
    {
      "awardValue": 0.00,
      "startDate": "2010-12-31",
      "endDate": "2018-12-30"
    },
    {
      "awardValue": 45.00,
      "startDate": "2018-12-31",
      "endDate": "2028-12-30"
    }
  ],
  "rateInformation": {
    "higherRateValue": 99999999999.99,
    "standardRateValue": 0.0,
    "guardianAllowanceRateValue": 123456.78
  },
  "paymentData": [
    {
      "amount": -111.11,
      "dateFrom": "2010-12-31",
      "dateTo": "2011-01-30",
      "chargeRef": "A-131234/35",
      "expectedCreditingDate": "2010-02-03",
      "returnIndicator": 0
    },
    {
      "amount": 222.22,
      "dateFrom": "2010-12-31",
      "dateTo": "2011-01-30",
      "chargeRef": "A-131234/35",
      "expectedCreditingDate": "2010-02-03",
      "returnIndicator": 0
    }
  ],
  "adjustmentType": [
    {
      "adjustmentAmount": 666666.66,
      "adjustmentStartDate": "2012-07-07",
      "adjustmentEndDate": "2013-02-28",
      "adjustmentReasonCode": "10"
    },
    {
      "adjustmentAmount": 444444.44,
      "adjustmentStartDate": "2013-03-01",
      "adjustmentEndDate": "2013-11-01",
      "adjustmentReasonCode": "10"
    }
  ]
}
